### PR TITLE
keep/dropMatches

### PR DESCRIPTION
**Pull request by andreavicini**

### CODE REVIEW

**Review by jorainer — CHANGES_REQUESTED** [review]
After some thoughts I think it might be better to have a single function `filterMatches` instead of two separate functions. `filterMatches` could have a parameter `keep` that, if `keep = TRUE` keeps matches matching the criteria and if `FALSE` drops them.

Could you please implement that @andreavicini and remove the two separate methods?

**Comment by andreavicini** [comment]
Hi, I pushed the new changes and I'd like to ask your opinion on the following thing. In the implementation of `addMatches` I assumed that the elements of `query` and `target` or of the column  `queryColname`/`targetColname` have to be unique. At the moment, If they are not `addMatches` will only add to `object@matches` the indexes corresponding to the first match  with the input `queryValues`, `targetValues`. Is this ok or should I allow all the matches to be added? In that case however it would be difficult for the user to assign the score to those matches (the input scores should have more elements than `queryValues`/`targetValues`. When for example the indexes are not univocally determined by one column but for example by two the user can still pass directly the indexes of the rows using parameter `isIndex`.

**Comment by jorainer** [comment]
I'm OK with the current implementation (i.e. that only the first match for `query` and `target` are added) - there is still the possibility to provide the indices and then the match is exactly defined. But this should be clearly stated in the documentation!

**Review by jorainer — APPROVED** [review]
Excellent! Thanks @andreavicini ! I will merge and update the documentation (regarding the uniqueness in `addMatch`) myself.

**Pull request merged**
