### PR TITLE
[fix] fix issue on vignette (issue #100)

### PR DESCRIPTION
**Pull request by RemyDeB**
Update scale_int to norm_int and add ... to function declaration

### CODE REVIEW

**Comment by jorainer** [comment]
thanks for the fix (and sorry for the late reply -> holidays).

**Review by jorainer — CHANGES_REQUESTED** [review]
Thanks for the fix - only, I would prefer if you keep the name of the function `scale_int` because `norm_int` might be misleading. In fact we're scaling the intensities and not really normalizing them. I had already some discussions at a conference where users/workshop attendees were confused by this `norm_int` function.

**Comment by RemyDeB** [comment]
I understand your concern, and I've made the necessary changes.
The function is now named "scale_int" instead of "norm_int".

**Review by jorainer — APPROVED** [review]
Thanks @RemyDeB for the fix!

**Pull request merged**
