### PR TITLE
Devel michael

### PR DESCRIPTION
**Pull request by michaelwitting**
Initial version for matching of formula

### CODE REVIEW

**Comment by michaelwitting** [comment]
@andreavicini and @jorainer please check if this is fine. Then I would add the unit tests and documentation.

**Comment by andreavicini** [comment]
It seems fine to me!

**Comment by jorainer** [comment]
Sorry for the very late reply! Looks good to me. This is performing an exact match between formulas right? Would it also make sense to define a "similarity score" for chemical formulas?

**Comment by michaelwitting** [comment]
Yes, it is only exact matches. No idea how a similarity score for chemical formulas should look like. I think exact matching is good enough.

**Comment by jorainer** [comment]
Sure - was only thinking if that would also be a thing :)

**Review by andreavicini — APPROVED** [review]
The PR looks fine to me!

**Review by jorainer — APPROVED** [review]
Looks good to me Michael! Thanks!

**Comment by jorainer** [comment]
@michaelwitting , I assume you're OK if I merge this? Note that this PR is labeled still as a "Draft pull request", does this mean you're still working on it?

**Comment by michaelwitting** [comment]
Sorry, forget to change back. Indeed you can merge.

**Pull request merged**
